remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta Mail TCK]
description: [Technology Compatibility Kit User's Guide for Jakarta Mail, Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/mail-tck
  download: https://github.com/eclipse-ee4j/mail-tck/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/mail-dev
  #javadocs:
  docs: https://eclipse-ee4j.github.io/mail-tck
  #faq:

include:
  - LICENSE.md
  - CONTRIBUTING.md
